### ISSUE TITLE
Worker names occur multiple times in pg_worker_list.conf using docker-compose

### ISSUE THREAD

**Issue by marcocitus** [heap/citus-docker#3]
When I run docker-compose, the pg_worker_list.conf on the master node are as follows:

```
citusdocker_citus_1 5432
citusdocker_citus2_1    5432
citus   5432
citus_1 5432
citus2  5432
citus2_1 5432
```

This is because the hostnames in /etc/hosts are defined in multiple ways and they all contain "citus".  reload-workers.sh greps /etc/hosts by "citus" to find the worker hostnames for pg_worker_reload.conf. However, if pg_worker_list.conf contains duplicates, CitusDB may attempt to place multiple replicas on the same host, which may cause warnings such as:

```
WARNING:  could not create shard on "citusworker1_1:5432"    
```

A possible fix would be to use grep $'\tcitusdocker', which returns only hosts whose name starts with citusdocker.

I'm using docker 1.6.2 and docker-compose 1.3.3

btw, this is an awesome image :)

**Comment by macobo** [comment]
Fixing this is a bit tricky - our own usecase is to inherit from this image, meaning that the prefix added by compose will be different from `citusdocker`.

If you can figure out a good fix for this (e.g. by better filtering hosts by IP), I'd be happy to accept a PR!

**Comment by macobo** [comment]
This should now be fixed, let me know if this solved your problem!
